[package]
name = "martin"
version = "0.5.0"
authors = ["Stepan Kuzmin <to.stepan.kuzmin@gmail.com>"]
edition = "2018"

[lib]
name = "martin"
path = "src/lib.rs"

[[bin]]
name = "martin"
path = "src/bin/main.rs"

[dependencies]
actix = "0.8"
actix-rt = "1.0"
actix-web = "1.0"
docopt = "1"
env_logger = "0.7"
futures = "0.1"
log = "0.4"
num_cpus = "1.11"
postgres = { version = "0.15", features = ["with-time", "with-uuid", "with-serde_json"] }
r2d2 = "0.8"
r2d2_postgres = "0.14"
semver = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
tilejson = "0.2"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "server"
harness = false